apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JWangSCW/airflow.git/airflow-k8s
    targetRevision: HEAD
    path: airflow-k8s
  destination:
    server: https://kubernetes.default.svc