apiVersion: v1
clusters:
- name: "kapsule-dataflow"
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJMU1EUXhOakV4TURNd04xb1hEVE0xTURReE5qRXhNRE13TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTFpFClhZcGZhdk43dElqRHY1aUdzMFdEeEREUTlGa3pNYnp2NUVnZDJXQ25HN1pUU2x5MDgwVmlwWWJCTGtQZWF3eTUKOURsSEZIME1uQW5FRHNyQTA0VjJsdndOYUxkZmFwZXR6RzJFZXlsTCt4MlZVQ0tkT2JxTm5xbGFseEhXKzlpKwp5ZU1zR1lhVktKcWkweGxHaHA1UVlFeGRlRzFKWWNVV0RvRHllYnBtQ051VVlXdDFHREFVYXJvYWhMRXVIZUdFClJVaTlzZmQvdGhHU0I2azVpSkQrUHdncDV4QUcva3ZyM1ZibnpPd0ZDMmNyTjZEa0MyY0w3K0wxcDJkeEdIc0YKZi9HMHpTTzUwR0svOEFvQ05XbzZkTzY2SXpMMVdCRlBWZnd5WU5oRnhya3dENUVmM3YzWm94M2MvNlFLdk43eApyeEUzWFVVaDMzV0dJZjlCUXAwQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJcm9MRzJ1eEc1SlBxY1ZxTFhQeGVxakp0aUxNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBdFoxMDJ3VEZJSURreXlCcnFiUVpsdFFKQTVhREFCclFlL3RsdzB3U0FiemxLWU44QgpEcEVFRHVJN1V5T3NOanFUMUpqRkFNWjMwQU5xL254Z3lDbmlFeDlsOWFvSFBBMjJUL20xbktDcnhmQk1UeXIrCjdGeER6czltb1JEVmpYb0l4a2JHNXBYUTZUV0EvZkxJWjZJVU9zYkF3Y1RoYzBaMmt3dVJEb01uc242WFJIVDYKTVpIL1plSTRzdGhVdDRNU2hibnRqdU5RdFR5N000LzVyUjlPdHhqWlBsVWVLcjhmbFR4L1FGMmtoWXZYRElwdQpRN2k4TmVZY2hZSGpTWXI2UmY5OUdlckVocEdZSnR5c2g3RjZCL3J0RzRGbVk4OUcwNmFRL2E5UFJUeUVYU09ICmVkODdNdjNiUTFybC9XNlVaSlQyZjhlUzJ5em1MUkhNY0lZUAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://01be0e19-5949-4f80-ac54-6c62ac0004b7.api.k8s.fr-par.scw.cloud:6443
contexts:
- name: admin@kapsule-dataflow
  context:
    cluster: "kapsule-dataflow"
    user: kapsule-dataflow-admin
current-context: admin@kapsule-dataflow
kind: Config
preferences: {}
users:
- name: kapsule-dataflow-admin
  user:
    token: cNbHSXcyIuurf7mbjQwPBXmdgZD1jhnYd7PDp9j20DdtounbMOSpLVDH